#!/usr/bin/env python
""" Print a short summary for one or more FITS files."""
import sys
if len(sys.argv) < 2:
    sys.exit('usage: finfo [filenames] ')

import pyfits

for filename in sys.argv[1:]:
    f = pyfits.open(filename)
    f.info()
    f.close()
