#!/usr/bin/env python
""" Print a short summary for one or more FITS files."""
from __future__ import print_function
import sys
if len(sys.argv) < 2:
    sys.exit('usage: finfo [filenames] ')

try:
    import pyfits as fits
except ImportError:
    import astropy.io.fits as fits

from barak.utilities import stats

for filename in sys.argv[1:]:
    f = fits.open(filename)
    results = filename + '\n'
    for j in range(len(f)):
        results += "  %-3d  %s\n"%(j, f[j]._summary())
        if f[j].data is not None:
            try:
                results = results +  '  ' + stats(f[j].data) + '\n'
            except TypeError:
                pass
    results = results[:-1]
    print(results)
    f.close()
