#!/usr/bin/env python
""" Print a short summary for one or more FITS files."""
from __future__ import print_function
import sys
if len(sys.argv) < 2:
    sys.exit('usage: finfo [filenames] ')

try:
    import pyfits
except ImportError:
    import astropy.io.fits as pyfits

for filename in sys.argv[1:]:
    f = pyfits.open(filename)
    f.info()
    f.close()
